from errors.base import WorkflowsBaseException


class CredentialsError(WorkflowsBaseException):
    pass
